apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskorbit-backend
  namespace: taskorbit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskorbit-backend
  template:
    metadata:
      labels:
        app: taskorbit-backend
    spec:
      containers:
      - name: taskorbit-backend
        image: taskorbit-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "taskorbit-database"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "taskorbit"
        - name: DB_PASSWORD
          value: "taskorbit123"
        - name: DB_NAME
          value: "taskorbit"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: taskorbit-backend
  namespace: taskorbit
spec:
  type: ClusterIP
  selector:
    app: taskorbit-backend
  ports:
  - port: 8080
    targetPort: 8080
