version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: taskorbit-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend-nestjs
      dockerfile: Dockerfile
    container_name: taskorbit-backend
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-changeme}
    depends_on:
      redis:
        condition: service_healthy
 