apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskorbit-database
  namespace: taskorbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskorbit-database
  template:
    metadata:
      labels:
        app: taskorbit-database
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "taskorbit"
        - name: POSTGRES_USER
          value: "taskorbit"
        - name: POSTGRES_PASSWORD
          value: "taskorbit123"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      volumes:
      - name: postgres-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: taskorbit-database
  namespace: taskorbit
spec:
  type: ClusterIP
  selector:
    app: taskorbit-database
  ports:
  - port: 5432
    targetPort: 5432
