apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskorbit-frontend
  namespace: taskorbit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskorbit-frontend
  template:
    metadata:
      labels:
        app: taskorbit-frontend
    spec:
      containers:
      - name: taskorbit-frontend
        image: taskorbit-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://taskorbit-backend:8080"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: taskorbit-frontend
  namespace: taskorbit
spec:
  type: LoadBalancer
  selector:
    app: taskorbit-frontend
  ports:
  - port: 80
    targetPort: 3000
