global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # TaskOrbit Backend
  - job_name: 'taskorbit-backend'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: '/api/health'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Node Exporter (if you want system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  # PostgreSQL (if you want database metrics)
  - job_name: 'postgres'
    static_configs:
      - targets: ['database:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s 